CREATE TABLE CUSTOMER (
    ID VARCHAR(30) PRIMARY KEY,
    PASSWORD VARCHAR(20),
    NAME VARCHAR(10),
    AGE INT,
    GENDER CHAR(1),
    EMAIL VARCHAR(50),
    PHONE VARCHAR(14),
    CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PRODUCT (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    PRICE INT,
    CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LASTUPDATEAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATEDBY VARCHAR(10)
);

CREATE TABLE CART (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID VARCHAR(30),
    PRODUCT_ID INT,
    QUANTITY INT,
    CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);